set(ITKBiasCorrection_LOADED 1)
set(ITKBiasCorrection_ENABLE_SHARED "1")
set(ITKBiasCorrection_DEPENDS "ITKCommon;ITKImageGrid;ITKImageIntensity;ITKOptimizers;ITKPolynomials")
set(ITKBiasCorrection_PUBLIC_DEPENDS "")
set(ITKBiasCorrection_TRANSITIVE_DEPENDS "ITKImageGrid;ITKImageIntensity;ITKOptimizers;ITKPolynomials")
set(ITKBiasCorrection_PRIVATE_DEPENDS "ITKCommon")
set(ITKBiasCorrection_LIBRARIES "ITKBiasCorrection")
set(ITKBiasCorrection_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/BiasCorrection/include")
set(ITKBiasCorrection_LIBRARY_DIRS "")
set(ITKBiasCorrection_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKBiasCorrection_TARGETS_FILE "")
set(ITKBiasCorrection_FACTORY_NAMES "")

