set(ITKBioCell_LOADED 1)
set(ITKBioCell_ENABLE_SHARED "1")
set(ITKBioCell_DEPENDS "ITKCommon;ITKMesh")
set(ITKBioCell_PUBLIC_DEPENDS "ITKMesh")
set(ITKBioCell_TRANSITIVE_DEPENDS "ITKMesh")
set(ITKBioCell_PRIVATE_DEPENDS "ITKCommon")
set(ITKBioCell_LIBRARIES "ITKBioCell")
set(ITKBioCell_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Segmentation/BioCell/include")
set(ITKBioCell_LIBRARY_DIRS "")
set(ITKBioCell_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKBioCell_TARGETS_FILE "")
set(ITKBioCell_FACTORY_NAMES "")

