set(ITKConvolution_LOADED 1)
set(ITKConvolution_ENABLE_SHARED "0")
set(ITKConvolution_DEPENDS "ITKFFT;ITKImageIntensity;ITKThresholding")
set(ITKConvolution_PUBLIC_DEPENDS "")
set(ITKConvolution_TRANSITIVE_DEPENDS "ITKFFT;ITKImageIntensity;ITKThresholding")
set(ITKConvolution_PRIVATE_DEPENDS "")
set(ITKConvolution_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKConvolution_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/Convolution/include")
set(ITKConvolution_LIBRARY_DIRS "")
set(ITKConvolution_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKConvolution_TARGETS_FILE "")
set(ITKConvolution_FACTORY_NAMES "")

