set(ITKCommon_LOADED 1)
set(ITKCommon_ENABLE_SHARED "1")
set(ITKCommon_DEPENDS "ITKDoubleConversion;ITKKWIML;ITKKWSys;ITKVNLInstantiation")
set(ITKCommon_PUBLIC_DEPENDS "ITKKWIML")
set(ITKCommon_TRANSITIVE_DEPENDS "ITKKWIML;ITKKWSys;ITKVNLInstantiation")
set(ITKCommon_PRIVATE_DEPENDS "ITKDoubleConversion")
set(ITKCommon_LIBRARIES "ITKCommon")
set(ITKCommon_INCLUDE_DIRS "/Users/kit/Documents/ITK/ITKbin/Modules/Core/Common;/Users/kit/Documents/ITK/InsightToolKit/Modules/Core/Common/include")
set(ITKCommon_LIBRARY_DIRS "")
set(ITKCommon_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKCommon_TARGETS_FILE "")
set(ITKCommon_FACTORY_NAMES "")

