set(ITKDeformableMesh_LOADED 1)
set(ITKDeformableMesh_ENABLE_SHARED "0")
set(ITKDeformableMesh_DEPENDS "ITKAnisotropicSmoothing;ITKImageFeature;ITKImageIntensity;ITKMesh;ITKThresholding")
set(ITKDeformableMesh_PUBLIC_DEPENDS "ITKAnisotropicSmoothing;ITKImageFeature;ITKImageIntensity;ITKMesh;ITKThresholding")
set(ITKDeformableMesh_TRANSITIVE_DEPENDS "ITKAnisotropicSmoothing;ITKImageFeature;ITKImageIntensity;ITKMesh;ITKThresholding")
set(ITKDeformableMesh_PRIVATE_DEPENDS "")
set(ITKDeformableMesh_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKMesh")
set(ITKDeformableMesh_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Segmentation/DeformableMesh/include")
set(ITKDeformableMesh_LIBRARY_DIRS "")
set(ITKDeformableMesh_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKDeformableMesh_TARGETS_FILE "")
set(ITKDeformableMesh_FACTORY_NAMES "")

