set(ITKDenoising_LOADED 1)
set(ITKDenoising_ENABLE_SHARED "0")
set(ITKDenoising_DEPENDS "ITKIOImageBase;ITKImageAdaptors;ITKImageGrid;ITKImageStatistics;ITKStatistics")
set(ITKDenoising_PUBLIC_DEPENDS "")
set(ITKDenoising_TRANSITIVE_DEPENDS "ITKIOImageBase;ITKImageAdaptors;ITKImageGrid;ITKImageStatistics;ITKStatistics")
set(ITKDenoising_PRIVATE_DEPENDS "")
set(ITKDenoising_LIBRARIES "ITKIOImageBase;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects")
set(ITKDenoising_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/Denoising/include")
set(ITKDenoising_LIBRARY_DIRS "")
set(ITKDenoising_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKDenoising_TARGETS_FILE "")
set(ITKDenoising_FACTORY_NAMES "")

