set(ITKDeconvolution_LOADED 1)
set(ITKDeconvolution_ENABLE_SHARED "0")
set(ITKDeconvolution_DEPENDS "ITKConvolution;ITKImageSources")
set(ITKDeconvolution_PUBLIC_DEPENDS "")
set(ITKDeconvolution_TRANSITIVE_DEPENDS "ITKConvolution;ITKImageSources")
set(ITKDeconvolution_PRIVATE_DEPENDS "")
set(ITKDeconvolution_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKDeconvolution_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/Deconvolution/include")
set(ITKDeconvolution_LIBRARY_DIRS "")
set(ITKDeconvolution_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKDeconvolution_TARGETS_FILE "")
set(ITKDeconvolution_FACTORY_NAMES "")

