set(ITKDisplacementField_LOADED 1)
set(ITKDisplacementField_ENABLE_SHARED "0")
set(ITKDisplacementField_DEPENDS "ITKImageGrid;ITKImageIntensity")
set(ITKDisplacementField_PUBLIC_DEPENDS "")
set(ITKDisplacementField_TRANSITIVE_DEPENDS "ITKImageGrid;ITKImageIntensity")
set(ITKDisplacementField_PRIVATE_DEPENDS "")
set(ITKDisplacementField_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKDisplacementField_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/DisplacementField/include")
set(ITKDisplacementField_LIBRARY_DIRS "")
set(ITKDisplacementField_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKDisplacementField_TARGETS_FILE "")
set(ITKDisplacementField_FACTORY_NAMES "")

