set(ITKFiniteDifference_LOADED 1)
set(ITKFiniteDifference_ENABLE_SHARED "0")
set(ITKFiniteDifference_DEPENDS "ITKCommon")
set(ITKFiniteDifference_PUBLIC_DEPENDS "")
set(ITKFiniteDifference_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKFiniteDifference_PRIVATE_DEPENDS "")
set(ITKFiniteDifference_LIBRARIES "ITKCommon")
set(ITKFiniteDifference_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Core/FiniteDifference/include")
set(ITKFiniteDifference_LIBRARY_DIRS "")
set(ITKFiniteDifference_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKFiniteDifference_TARGETS_FILE "")
set(ITKFiniteDifference_FACTORY_NAMES "")

