set(ITKFEMRegistration_LOADED 1)
set(ITKFEMRegistration_ENABLE_SHARED "0")
set(ITKFEMRegistration_DEPENDS "ITKFEM;ITKImageFeature;ITKImageStatistics;ITKPDEDeformableRegistration;ITKSpatialObjects")
set(ITKFEMRegistration_PUBLIC_DEPENDS "ITKFEM;ITKImageFeature;ITKImageStatistics;ITKPDEDeformableRegistration;ITKSpatialObjects")
set(ITKFEMRegistration_TRANSITIVE_DEPENDS "ITKFEM;ITKImageFeature;ITKImageStatistics;ITKPDEDeformableRegistration;ITKSpatialObjects")
set(ITKFEMRegistration_PRIVATE_DEPENDS "")
set(ITKFEMRegistration_LIBRARIES "ITKFEM;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKMesh;ITKOptimizers")
set(ITKFEMRegistration_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Registration/FEM/include")
set(ITKFEMRegistration_LIBRARY_DIRS "")
set(ITKFEMRegistration_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKFEMRegistration_TARGETS_FILE "")
set(ITKFEMRegistration_FACTORY_NAMES "")

