set(ITKGPUThresholding_LOADED 1)
set(ITKGPUThresholding_ENABLE_SHARED "0")
set(ITKGPUThresholding_DEPENDS "ITKCommon;ITKGPUCommon;ITKThresholding")
set(ITKGPUThresholding_PUBLIC_DEPENDS "ITKCommon;ITKGPUCommon")
set(ITKGPUThresholding_TRANSITIVE_DEPENDS "ITKCommon;ITKGPUCommon;ITKThresholding")
set(ITKGPUThresholding_PRIVATE_DEPENDS "")
set(ITKGPUThresholding_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKGPUThresholding_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/GPUThresholding/include")
set(ITKGPUThresholding_LIBRARY_DIRS "")
set(ITKGPUThresholding_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKGPUThresholding_TARGETS_FILE "")
set(ITKGPUThresholding_FACTORY_NAMES "")

