set(ITKGPUCommon_LOADED 1)
set(ITKGPUCommon_ENABLE_SHARED "0")
set(ITKGPUCommon_DEPENDS "ITKCommon")
set(ITKGPUCommon_PUBLIC_DEPENDS "ITKCommon")
set(ITKGPUCommon_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKGPUCommon_PRIVATE_DEPENDS "")
set(ITKGPUCommon_LIBRARIES "ITKCommon")
set(ITKGPUCommon_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Core/GPUCommon/include")
set(ITKGPUCommon_LIBRARY_DIRS "")
set(ITKGPUCommon_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKGPUCommon_TARGETS_FILE "")
set(ITKGPUCommon_FACTORY_NAMES "")

