set(ITKGDCM_LOADED 1)
set(ITKGDCM_ENABLE_SHARED "0")
set(ITKGDCM_DEPENDS "ITKExpat;ITKZLIB")
set(ITKGDCM_PUBLIC_DEPENDS "ITKExpat;ITKZLIB")
set(ITKGDCM_TRANSITIVE_DEPENDS "ITKExpat;ITKZLIB")
set(ITKGDCM_PRIVATE_DEPENDS "")
set(ITKGDCM_LIBRARIES "gdcmDICT;gdcmMSFF")
set(ITKGDCM_INCLUDE_DIRS "/Users/kit/Documents/ITK/ITKbin/Modules/ThirdParty/GDCM;/Users/kit/Documents/ITK/ITKbin/Modules/ThirdParty/GDCM/src/gdcm/Source/Common;/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat;/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary;/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/GDCM/src/gdcm/Source/Common;/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/GDCM/src/gdcm/Source/InformationObjectDefinition;/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/GDCM/src/gdcm/Source/MessageExchangeDefinition;/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition")
set(ITKGDCM_LIBRARY_DIRS "")
set(ITKGDCM_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKGDCM_TARGETS_FILE "")
set(ITKGDCM_FACTORY_NAMES "")

