set(ITKImageCompose_LOADED 1)
set(ITKImageCompose_ENABLE_SHARED "0")
set(ITKImageCompose_DEPENDS "ITKImageFilterBase")
set(ITKImageCompose_PUBLIC_DEPENDS "")
set(ITKImageCompose_TRANSITIVE_DEPENDS "ITKImageFilterBase")
set(ITKImageCompose_PRIVATE_DEPENDS "")
set(ITKImageCompose_LIBRARIES "ITKCommon")
set(ITKImageCompose_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/ImageCompose/include")
set(ITKImageCompose_LIBRARY_DIRS "")
set(ITKImageCompose_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKImageCompose_TARGETS_FILE "")
set(ITKImageCompose_FACTORY_NAMES "")

