set(ITKIOBioRad_LOADED 1)
set(ITKIOBioRad_ENABLE_SHARED "1")
set(ITKIOBioRad_DEPENDS "ITKIOImageBase")
set(ITKIOBioRad_PUBLIC_DEPENDS "")
set(ITKIOBioRad_TRANSITIVE_DEPENDS "")
set(ITKIOBioRad_PRIVATE_DEPENDS "ITKIOImageBase")
set(ITKIOBioRad_LIBRARIES "ITKIOBioRad")
set(ITKIOBioRad_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/IO/BioRad/include")
set(ITKIOBioRad_LIBRARY_DIRS "")
set(ITKIOBioRad_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKIOBioRad_TARGETS_FILE "")
set(ITKIOBioRad_FACTORY_NAMES "ImageIO::BioRad")

