set(ITKImageFunction_LOADED 1)
set(ITKImageFunction_ENABLE_SHARED "0")
set(ITKImageFunction_DEPENDS "ITKImageAdaptors;ITKStatistics;ITKTransform")
set(ITKImageFunction_PUBLIC_DEPENDS "")
set(ITKImageFunction_TRANSITIVE_DEPENDS "ITKImageAdaptors;ITKStatistics;ITKTransform")
set(ITKImageFunction_PRIVATE_DEPENDS "")
set(ITKImageFunction_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform")
set(ITKImageFunction_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Core/ImageFunction/include")
set(ITKImageFunction_LIBRARY_DIRS "")
set(ITKImageFunction_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKImageFunction_TARGETS_FILE "")
set(ITKImageFunction_FACTORY_NAMES "")

