set(ITKImageLabel_LOADED 1)
set(ITKImageLabel_ENABLE_SHARED "0")
set(ITKImageLabel_DEPENDS "ITKImageIntensity")
set(ITKImageLabel_PUBLIC_DEPENDS "")
set(ITKImageLabel_TRANSITIVE_DEPENDS "ITKImageIntensity")
set(ITKImageLabel_PRIVATE_DEPENDS "")
set(ITKImageLabel_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKImageLabel_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/ImageLabel/include")
set(ITKImageLabel_LIBRARY_DIRS "")
set(ITKImageLabel_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKImageLabel_TARGETS_FILE "")
set(ITKImageLabel_FACTORY_NAMES "")

