set(ITKIOSiemens_LOADED 1)
set(ITKIOSiemens_ENABLE_SHARED "1")
set(ITKIOSiemens_DEPENDS "ITKIOIPL;ITKIOImageBase")
set(ITKIOSiemens_PUBLIC_DEPENDS "")
set(ITKIOSiemens_TRANSITIVE_DEPENDS "")
set(ITKIOSiemens_PRIVATE_DEPENDS "ITKIOIPL;ITKIOImageBase")
set(ITKIOSiemens_LIBRARIES "ITKIOSiemens")
set(ITKIOSiemens_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/IO/Siemens/include")
set(ITKIOSiemens_LIBRARY_DIRS "")
set(ITKIOSiemens_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKIOSiemens_TARGETS_FILE "")
set(ITKIOSiemens_FACTORY_NAMES "")

