set(ITKImageFeature_LOADED 1)
set(ITKImageFeature_ENABLE_SHARED "0")
set(ITKImageFeature_DEPENDS "ITKImageGradient;ITKImageSources;ITKImageStatistics;ITKMesh;ITKSmoothing")
set(ITKImageFeature_PUBLIC_DEPENDS "")
set(ITKImageFeature_TRANSITIVE_DEPENDS "ITKImageGradient;ITKImageSources;ITKImageStatistics;ITKMesh;ITKSmoothing")
set(ITKImageFeature_PRIVATE_DEPENDS "")
set(ITKImageFeature_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKMesh")
set(ITKImageFeature_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/ImageFeature/include")
set(ITKImageFeature_LIBRARY_DIRS "")
set(ITKImageFeature_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKImageFeature_TARGETS_FILE "")
set(ITKImageFeature_FACTORY_NAMES "")

