set(ITKImageFusion_LOADED 1)
set(ITKImageFusion_ENABLE_SHARED "0")
set(ITKImageFusion_DEPENDS "ITKBinaryMathematicalMorphology;ITKImageLabel")
set(ITKImageFusion_PUBLIC_DEPENDS "")
set(ITKImageFusion_TRANSITIVE_DEPENDS "ITKBinaryMathematicalMorphology;ITKImageLabel")
set(ITKImageFusion_PRIVATE_DEPENDS "")
set(ITKImageFusion_LIBRARIES "ITKLabelMap;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKImageFusion_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/ImageFusion/include")
set(ITKImageFusion_LIBRARY_DIRS "")
set(ITKImageFusion_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKImageFusion_TARGETS_FILE "")
set(ITKImageFusion_FACTORY_NAMES "")

