set(ITKIOMesh_LOADED 1)
set(ITKIOMesh_ENABLE_SHARED "1")
set(ITKIOMesh_DEPENDS "ITKDoubleConversion;ITKGIFTI;ITKIOImageBase;ITKMesh")
set(ITKIOMesh_PUBLIC_DEPENDS "")
set(ITKIOMesh_TRANSITIVE_DEPENDS "ITKMesh")
set(ITKIOMesh_PRIVATE_DEPENDS "ITKDoubleConversion;ITKGIFTI;ITKIOImageBase")
set(ITKIOMesh_LIBRARIES "ITKIOMesh")
set(ITKIOMesh_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/IO/Mesh/include")
set(ITKIOMesh_LIBRARY_DIRS "")
set(ITKIOMesh_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKIOMesh_TARGETS_FILE "")
set(ITKIOMesh_FACTORY_NAMES "")

