set(ITKIOMeta_LOADED 1)
set(ITKIOMeta_ENABLE_SHARED "1")
set(ITKIOMeta_DEPENDS "ITKIOImageBase;ITKMetaIO")
set(ITKIOMeta_PUBLIC_DEPENDS "ITKMetaIO")
set(ITKIOMeta_TRANSITIVE_DEPENDS "ITKMetaIO")
set(ITKIOMeta_PRIVATE_DEPENDS "ITKIOImageBase")
set(ITKIOMeta_LIBRARIES "ITKIOMeta")
set(ITKIOMeta_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/IO/Meta/include")
set(ITKIOMeta_LIBRARY_DIRS "")
set(ITKIOMeta_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKIOMeta_TARGETS_FILE "")
set(ITKIOMeta_FACTORY_NAMES "ImageIO::Meta")

