set(ITKImageGradient_LOADED 1)
set(ITKImageGradient_ENABLE_SHARED "0")
set(ITKImageGradient_DEPENDS "ITKImageAdaptors;ITKImageIntensity;ITKSmoothing")
set(ITKImageGradient_PUBLIC_DEPENDS "")
set(ITKImageGradient_TRANSITIVE_DEPENDS "ITKImageAdaptors;ITKImageIntensity;ITKSmoothing")
set(ITKImageGradient_PRIVATE_DEPENDS "")
set(ITKImageGradient_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKImageGradient_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/ImageGradient/include")
set(ITKImageGradient_LIBRARY_DIRS "")
set(ITKImageGradient_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKImageGradient_TARGETS_FILE "")
set(ITKImageGradient_FACTORY_NAMES "")

