set(ITKImageNoise_LOADED 1)
set(ITKImageNoise_ENABLE_SHARED "0")
set(ITKImageNoise_DEPENDS "ITKStatistics")
set(ITKImageNoise_PUBLIC_DEPENDS "")
set(ITKImageNoise_TRANSITIVE_DEPENDS "ITKStatistics")
set(ITKImageNoise_PRIVATE_DEPENDS "")
set(ITKImageNoise_LIBRARIES "ITKStatistics")
set(ITKImageNoise_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/ImageNoise/include")
set(ITKImageNoise_LIBRARY_DIRS "")
set(ITKImageNoise_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKImageNoise_TARGETS_FILE "")
set(ITKImageNoise_FACTORY_NAMES "")

