set(ITKKLMRegionGrowing_LOADED 1)
set(ITKKLMRegionGrowing_ENABLE_SHARED "1")
set(ITKKLMRegionGrowing_DEPENDS "ITKCommon")
set(ITKKLMRegionGrowing_PUBLIC_DEPENDS "ITKCommon")
set(ITKKLMRegionGrowing_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKKLMRegionGrowing_PRIVATE_DEPENDS "")
set(ITKKLMRegionGrowing_LIBRARIES "ITKKLMRegionGrowing")
set(ITKKLMRegionGrowing_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Segmentation/KLMRegionGrowing/include")
set(ITKKLMRegionGrowing_LIBRARY_DIRS "")
set(ITKKLMRegionGrowing_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKKLMRegionGrowing_TARGETS_FILE "")
set(ITKKLMRegionGrowing_FACTORY_NAMES "")

