set(ITKLevelSets_LOADED 1)
set(ITKLevelSets_ENABLE_SHARED "0")
set(ITKLevelSets_DEPENDS "ITKAnisotropicSmoothing;ITKDistanceMap;ITKFastMarching;ITKFiniteDifference;ITKIOImageBase;ITKImageCompare;ITKImageFeature;ITKNarrowBand;ITKOptimizers;ITKSignedDistanceFunction;ITKThresholding")
set(ITKLevelSets_PUBLIC_DEPENDS "ITKAnisotropicSmoothing;ITKDistanceMap;ITKFastMarching;ITKFiniteDifference;ITKImageCompare;ITKImageFeature;ITKNarrowBand;ITKOptimizers;ITKSignedDistanceFunction;ITKThresholding")
set(ITKLevelSets_TRANSITIVE_DEPENDS "ITKAnisotropicSmoothing;ITKDistanceMap;ITKFastMarching;ITKFiniteDifference;ITKIOImageBase;ITKImageCompare;ITKImageFeature;ITKNarrowBand;ITKOptimizers;ITKSignedDistanceFunction;ITKThresholding")
set(ITKLevelSets_PRIVATE_DEPENDS "")
set(ITKLevelSets_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKLabelMap;ITKSpatialObjects;ITKPath;ITKMesh;ITKQuadEdgeMesh;ITKIOImageBase;ITKOptimizers")
set(ITKLevelSets_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Segmentation/LevelSets/include")
set(ITKLevelSets_LIBRARY_DIRS "")
set(ITKLevelSets_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKLevelSets_TARGETS_FILE "")
set(ITKLevelSets_FACTORY_NAMES "")

