set(ITKLabelMap_LOADED 1)
set(ITKLabelMap_ENABLE_SHARED "1")
set(ITKLabelMap_DEPENDS "ITKStatistics;ITKTransform")
set(ITKLabelMap_PUBLIC_DEPENDS "")
set(ITKLabelMap_TRANSITIVE_DEPENDS "ITKTransform")
set(ITKLabelMap_PRIVATE_DEPENDS "ITKStatistics")
set(ITKLabelMap_LIBRARIES "ITKLabelMap")
set(ITKLabelMap_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/LabelMap/include")
set(ITKLabelMap_LIBRARY_DIRS "")
set(ITKLabelMap_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKLabelMap_TARGETS_FILE "")
set(ITKLabelMap_FACTORY_NAMES "")

