set(ITKMetaIO_LOADED 1)
set(ITKMetaIO_ENABLE_SHARED "0")
set(ITKMetaIO_DEPENDS "ITKZLIB")
set(ITKMetaIO_PUBLIC_DEPENDS "ITKZLIB")
set(ITKMetaIO_TRANSITIVE_DEPENDS "ITKZLIB")
set(ITKMetaIO_PRIVATE_DEPENDS "")
set(ITKMetaIO_LIBRARIES "ITKMetaIO")
set(ITKMetaIO_INCLUDE_DIRS "/Users/kit/Documents/ITK/ITKbin/Modules/ThirdParty/MetaIO/src/MetaIO/src;/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/MetaIO/src/MetaIO/src")
set(ITKMetaIO_LIBRARY_DIRS "")
set(ITKMetaIO_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKMetaIO_TARGETS_FILE "")
set(ITKMetaIO_FACTORY_NAMES "")

