set(ITKMesh_LOADED 1)
set(ITKMesh_ENABLE_SHARED "1")
set(ITKMesh_DEPENDS "ITKTransform")
set(ITKMesh_PUBLIC_DEPENDS "")
set(ITKMesh_TRANSITIVE_DEPENDS "")
set(ITKMesh_PRIVATE_DEPENDS "ITKTransform")
set(ITKMesh_LIBRARIES "ITKMesh")
set(ITKMesh_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Core/Mesh/include")
set(ITKMesh_LIBRARY_DIRS "")
set(ITKMesh_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKMesh_TARGETS_FILE "")
set(ITKMesh_FACTORY_NAMES "")

