set(ITKNetlib_LOADED 1)
set(ITKNetlib_ENABLE_SHARED "0")
set(ITKNetlib_DEPENDS "ITKVNL")
set(ITKNetlib_PUBLIC_DEPENDS "ITKVNL")
set(ITKNetlib_TRANSITIVE_DEPENDS "ITKVNL")
set(ITKNetlib_PRIVATE_DEPENDS "")
set(ITKNetlib_LIBRARIES "itkNetlibSlatec")
set(ITKNetlib_INCLUDE_DIRS "/Users/kit/Documents/ITK/ITKbin/Modules/ThirdParty/Netlib")
set(ITKNetlib_LIBRARY_DIRS "")
set(ITKNetlib_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKNetlib_TARGETS_FILE "")
set(ITKNetlib_FACTORY_NAMES "")

