set(ITKNrrdIO_LOADED 1)
set(ITKNrrdIO_ENABLE_SHARED "0")
set(ITKNrrdIO_DEPENDS "ITKZLIB")
set(ITKNrrdIO_PUBLIC_DEPENDS "ITKZLIB")
set(ITKNrrdIO_TRANSITIVE_DEPENDS "ITKZLIB")
set(ITKNrrdIO_PRIVATE_DEPENDS "")
set(ITKNrrdIO_LIBRARIES "ITKNrrdIO")
set(ITKNrrdIO_INCLUDE_DIRS "/Users/kit/Documents/ITK/ITKbin/Modules/ThirdParty/NrrdIO/src/NrrdIO;/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/NrrdIO/src/NrrdIO")
set(ITKNrrdIO_LIBRARY_DIRS "")
set(ITKNrrdIO_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKNrrdIO_TARGETS_FILE "")
set(ITKNrrdIO_FACTORY_NAMES "")

