set(ITKOptimizers_LOADED 1)
set(ITKOptimizers_ENABLE_SHARED "1")
set(ITKOptimizers_DEPENDS "ITKStatistics")
set(ITKOptimizers_PUBLIC_DEPENDS "ITKStatistics")
set(ITKOptimizers_TRANSITIVE_DEPENDS "ITKStatistics")
set(ITKOptimizers_PRIVATE_DEPENDS "")
set(ITKOptimizers_LIBRARIES "ITKOptimizers")
set(ITKOptimizers_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Numerics/Optimizers/include")
set(ITKOptimizers_LIBRARY_DIRS "")
set(ITKOptimizers_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKOptimizers_TARGETS_FILE "")
set(ITKOptimizers_FACTORY_NAMES "")

