set(ITKOptimizersv4_LOADED 1)
set(ITKOptimizersv4_ENABLE_SHARED "1")
set(ITKOptimizersv4_DEPENDS "ITKCommon;ITKDisplacementField;ITKImageGrid;ITKLIBLBFGS;ITKOptimizers;ITKTransform")
set(ITKOptimizersv4_PUBLIC_DEPENDS "ITKOptimizers")
set(ITKOptimizersv4_TRANSITIVE_DEPENDS "ITKCommon;ITKDisplacementField;ITKImageGrid;ITKOptimizers;ITKTransform")
set(ITKOptimizersv4_PRIVATE_DEPENDS "ITKLIBLBFGS")
set(ITKOptimizersv4_LIBRARIES "ITKOptimizersv4")
set(ITKOptimizersv4_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Numerics/Optimizersv4/include")
set(ITKOptimizersv4_LIBRARY_DIRS "")
set(ITKOptimizersv4_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKOptimizersv4_TARGETS_FILE "")
set(ITKOptimizersv4_FACTORY_NAMES "")

