set(ITKPath_LOADED 1)
set(ITKPath_ENABLE_SHARED "0")
set(ITKPath_DEPENDS "ITKCommon;ITKImageFunction")
set(ITKPath_PUBLIC_DEPENDS "")
set(ITKPath_TRANSITIVE_DEPENDS "ITKImageFunction")
set(ITKPath_PRIVATE_DEPENDS "ITKCommon")
set(ITKPath_LIBRARIES "ITKPath")
set(ITKPath_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/Path/include")
set(ITKPath_LIBRARY_DIRS "")
set(ITKPath_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKPath_TARGETS_FILE "")
set(ITKPath_FACTORY_NAMES "")

