set(ITKQuadEdgeMeshFiltering_LOADED 1)
set(ITKQuadEdgeMeshFiltering_ENABLE_SHARED "0")
set(ITKQuadEdgeMeshFiltering_DEPENDS "ITKMesh;ITKQuadEdgeMesh")
set(ITKQuadEdgeMeshFiltering_PUBLIC_DEPENDS "ITKMesh")
set(ITKQuadEdgeMeshFiltering_TRANSITIVE_DEPENDS "ITKMesh;ITKQuadEdgeMesh")
set(ITKQuadEdgeMeshFiltering_PRIVATE_DEPENDS "")
set(ITKQuadEdgeMeshFiltering_LIBRARIES "ITKMesh;ITKQuadEdgeMesh")
set(ITKQuadEdgeMeshFiltering_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/QuadEdgeMeshFiltering/include")
set(ITKQuadEdgeMeshFiltering_LIBRARY_DIRS "")
set(ITKQuadEdgeMeshFiltering_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKQuadEdgeMeshFiltering_TARGETS_FILE "")
set(ITKQuadEdgeMeshFiltering_FACTORY_NAMES "")

