set(ITKSpatialFunction_LOADED 1)
set(ITKSpatialFunction_ENABLE_SHARED "0")
set(ITKSpatialFunction_DEPENDS "ITKImageFunction")
set(ITKSpatialFunction_PUBLIC_DEPENDS "")
set(ITKSpatialFunction_TRANSITIVE_DEPENDS "ITKImageFunction")
set(ITKSpatialFunction_PRIVATE_DEPENDS "")
set(ITKSpatialFunction_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform")
set(ITKSpatialFunction_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Filtering/SpatialFunction/include")
set(ITKSpatialFunction_LIBRARY_DIRS "")
set(ITKSpatialFunction_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKSpatialFunction_TARGETS_FILE "")
set(ITKSpatialFunction_FACTORY_NAMES "")

