set(ITKSpatialObjects_LOADED 1)
set(ITKSpatialObjects_ENABLE_SHARED "0")
set(ITKSpatialObjects_DEPENDS "ITKCommon;ITKImageFunction;ITKMesh;ITKMetaIO;ITKTransform")
set(ITKSpatialObjects_PUBLIC_DEPENDS "ITKTransform")
set(ITKSpatialObjects_TRANSITIVE_DEPENDS "ITKImageFunction;ITKMetaIO;ITKTransform")
set(ITKSpatialObjects_PRIVATE_DEPENDS "ITKCommon;ITKMesh")
set(ITKSpatialObjects_LIBRARIES "ITKSpatialObjects")
set(ITKSpatialObjects_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Core/SpatialObjects/include")
set(ITKSpatialObjects_LIBRARY_DIRS "")
set(ITKSpatialObjects_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKSpatialObjects_TARGETS_FILE "")
set(ITKSpatialObjects_FACTORY_NAMES "")

