set(ITKTransform_LOADED 1)
set(ITKTransform_ENABLE_SHARED "1")
set(ITKTransform_DEPENDS "ITKCommon;ITKImageFilterBase;ITKStatistics")
set(ITKTransform_PUBLIC_DEPENDS "ITKCommon")
set(ITKTransform_TRANSITIVE_DEPENDS "ITKCommon;ITKImageFilterBase;ITKStatistics")
set(ITKTransform_PRIVATE_DEPENDS "")
set(ITKTransform_LIBRARIES "ITKTransform")
set(ITKTransform_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Core/Transform/include")
set(ITKTransform_LIBRARY_DIRS "")
set(ITKTransform_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKTransform_TARGETS_FILE "")
set(ITKTransform_FACTORY_NAMES "")

