set(ITKTransformFactory_LOADED 1)
set(ITKTransformFactory_ENABLE_SHARED "0")
set(ITKTransformFactory_DEPENDS "ITKCommon;ITKDisplacementField;ITKTransform")
set(ITKTransformFactory_PUBLIC_DEPENDS "ITKCommon;ITKTransform")
set(ITKTransformFactory_TRANSITIVE_DEPENDS "ITKCommon;ITKDisplacementField;ITKTransform")
set(ITKTransformFactory_PRIVATE_DEPENDS "")
set(ITKTransformFactory_LIBRARIES "ITKTransformFactory")
set(ITKTransformFactory_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/IO/TransformFactory/include")
set(ITKTransformFactory_LIBRARY_DIRS "")
set(ITKTransformFactory_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKTransformFactory_TARGETS_FILE "")
set(ITKTransformFactory_FACTORY_NAMES "")

