set(ITKVNLInstantiation_LOADED 1)
set(ITKVNLInstantiation_ENABLE_SHARED "0")
set(ITKVNLInstantiation_DEPENDS "ITKVNL")
set(ITKVNLInstantiation_PUBLIC_DEPENDS "ITKVNL")
set(ITKVNLInstantiation_TRANSITIVE_DEPENDS "ITKVNL")
set(ITKVNLInstantiation_PRIVATE_DEPENDS "")
set(ITKVNLInstantiation_LIBRARIES "itkvnl_algo;itkvnl;itkv3p_netlib;itknetlib;itkvcl")
set(ITKVNLInstantiation_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/VNLInstantiation/include")
set(ITKVNLInstantiation_LIBRARY_DIRS "")
set(ITKVNLInstantiation_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKVNLInstantiation_TARGETS_FILE "")
set(ITKVNLInstantiation_FACTORY_NAMES "")

