set(ITKVideoIO_LOADED 1)
set(ITKVideoIO_ENABLE_SHARED "1")
set(ITKVideoIO_DEPENDS "ITKIOImageBase;ITKVideoCore")
set(ITKVideoIO_PUBLIC_DEPENDS "ITKIOImageBase;ITKVideoCore")
set(ITKVideoIO_TRANSITIVE_DEPENDS "ITKIOImageBase;ITKVideoCore")
set(ITKVideoIO_PRIVATE_DEPENDS "")
set(ITKVideoIO_LIBRARIES "ITKVideoIO")
set(ITKVideoIO_INCLUDE_DIRS "/Users/kit/Documents/ITK/InsightToolKit/Modules/Video/IO/include")
set(ITKVideoIO_LIBRARY_DIRS "")
set(ITKVideoIO_RUNTIME_LIBRARY_DIRS "/Users/kit/Documents/ITK/ITKbin/lib")
set(ITKVideoIO_TARGETS_FILE "")
set(ITKVideoIO_FACTORY_NAMES "")

