# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "OFF")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "OFF")
set(CPACK_BINARY_PACKAGEMAKER "OFF")
set(CPACK_BINARY_PRODUCTBUILD "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/Users/kit/Documents/ITK/InsightToolKit;/Users/kit/Documents/ITK/ITKbin")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/ITKDCMTK/;/ITKDeprecated/;/ITKIODCMTK/;/ITKIOPhilipsREC/;/ITKIOTransformMINC/;/ITKLevelSetsv4Visualization/;/ITKOpenJPEG/;/ITKReview/;/ITKV3Compatibility/;/ITKVideoBridgeOpenCV/;/ITKVideoBridgeVXL/;/ITKVtkGlue/;/\\.git")
set(CPACK_INSTALLED_DIRECTORIES "/Users/kit/Documents/ITK/InsightToolKit;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/Users/kit/Documents/ITK/InsightToolKit/CMake;/Users/kit/Documents/ITK/InsightToolKit/CMake")
set(CPACK_NSIS_DISPLAY_NAME "ITK-4.13")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "ITK-4.13")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/kit/Documents/ITK/ITKbin/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "Insight Software Consortium <community@itk.org>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/kit/Documents/ITK/InsightToolKit/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Insight Toolkit version 4")
set(CPACK_PACKAGE_FILE_NAME "ITK-4.13.0-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "ITK-4.13")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "ITK-4.13")
set(CPACK_PACKAGE_NAME "ITK")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "ISC")
set(CPACK_PACKAGE_VERSION "4.13.0")
set(CPACK_PACKAGE_VERSION_MAJOR "4")
set(CPACK_PACKAGE_VERSION_MINOR "13")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/kit/Documents/ITK/InsightToolKit/LICENSE")
set(CPACK_RESOURCE_FILE_README "/Applications/CMake.app/Contents/share/cmake-3.13/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/Applications/CMake.app/Contents/share/cmake-3.13/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/ITKDCMTK/;/ITKDeprecated/;/ITKIODCMTK/;/ITKIOPhilipsREC/;/ITKIOTransformMINC/;/ITKLevelSetsv4Visualization/;/ITKOpenJPEG/;/ITKReview/;/ITKV3Compatibility/;/ITKVideoBridgeOpenCV/;/ITKVideoBridgeVXL/;/ITKVtkGlue/;/\\.git")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/kit/Documents/ITK/InsightToolKit;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/kit/Documents/ITK/ITKbin/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "ITK-4.13.0-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/kit/Documents/ITK/ITKbin/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
