# Generated by CMake, do not edit!# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget itkdouble-conversion itksys itkvcl itkv3p_netlib itktestlib itkvnl itkvnl_algo itknetlib ITKVNLInstantiation ITKCommon itkNetlibSlatec ITKStatistics ITKTransform ITKLabelMap ITKMesh itkzlib ITKMetaIO ITKSpatialObjects ITKPath ITKQuadEdgeMesh ITKIOImageBase ITKOptimizers ITKPolynomials ITKBiasCorrection ITKBioCell ITKDICOMParser ITKEXPAT ITKIOXML ITKIOSpatialObjects ITKFEM gdcmCommon gdcmDICT gdcmDSED gdcmIOD gdcmMEXD gdcmMSFF gdcmcharls gdcmjpeg12 gdcmjpeg16 gdcmjpeg8 itkgdcmopenjp2 gdcmsocketxx gdcmuuid ITKznz ITKniftiio ITKgiftiio GTest::GTest GTest::Main hdf5-static hdf5_cpp-static ITKIOBMP ITKIOBioRad ITKIOBruker ITKIOCSV ITKIOGDCM ITKIOIPL ITKIOGE ITKIOGIPL ITKIOHDF5 itkjpeg ITKIOJPEG itktiff ITKIOTIFF ITKIOLSM itkminc2 ITKIOMINC ITKIOMRC ITKIOMesh ITKIOMeta ITKIONIFTI ITKNrrdIO ITKIONRRD itkpng ITKIOPNG ITKIOSiemens ITKIOStimulate ITKTransformFactory ITKIOTransformBase ITKIOTransformHDF5 ITKIOTransformInsightLegacy ITKIOTransformMatlab ITKIOVTK ITKKLMRegionGrowing itklbfgs ITKOptimizersv4 itkTestDriver ITKVTK ITKVideoCore ITKVideoIO ITKWatersheds)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target itkdouble-conversion
add_library(itkdouble-conversion STATIC IMPORTED)

# Create imported target itksys
add_library(itksys STATIC IMPORTED)

set_target_properties(itksys PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/ITKbin/Modules/ThirdParty/KWSys/src/KWSys"
)

# Create imported target itkvcl
add_library(itkvcl STATIC IMPORTED)

set_target_properties(itkvcl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/VNL/src/vxl/vcl"
)

# Create imported target itkv3p_netlib
add_library(itkv3p_netlib STATIC IMPORTED)

set_target_properties(itkv3p_netlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/VNL/src/vxl/v3p/netlib"
)

# Create imported target itktestlib
add_library(itktestlib STATIC IMPORTED)

set_target_properties(itktestlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/VNL/src/vxl/core/testlib"
)

# Create imported target itkvnl
add_library(itkvnl STATIC IMPORTED)

set_target_properties(itkvnl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/VNL/src/vxl/core/vnl"
)

# Create imported target itkvnl_algo
add_library(itkvnl_algo STATIC IMPORTED)

set_target_properties(itkvnl_algo PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo"
)

# Create imported target itknetlib
add_library(itknetlib STATIC IMPORTED)

set_target_properties(itknetlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/VNL/src/vxl/v3p/netlib"
)

# Create imported target ITKVNLInstantiation
add_library(ITKVNLInstantiation STATIC IMPORTED)

set_target_properties(ITKVNLInstantiation PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkvnl_algo;itkvnl;itkv3p_netlib;itknetlib;itkvcl;itkvnl_algo;itkvnl;itkv3p_netlib;itknetlib;itkvcl"
)

# Create imported target ITKCommon
add_library(ITKCommon STATIC IMPORTED)

set_target_properties(ITKCommon PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:itkdouble-conversion>;itksys;ITKVNLInstantiation;-lm"
)

# Create imported target itkNetlibSlatec
add_library(itkNetlibSlatec STATIC IMPORTED)

set_target_properties(itkNetlibSlatec PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkv3p_netlib"
)

# Create imported target ITKStatistics
add_library(ITKStatistics STATIC IMPORTED)

set_target_properties(ITKStatistics PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon;itkNetlibSlatec"
)

# Create imported target ITKTransform
add_library(ITKTransform STATIC IMPORTED)

set_target_properties(ITKTransform PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon"
)

# Create imported target ITKLabelMap
add_library(ITKLabelMap STATIC IMPORTED)

set_target_properties(ITKLabelMap PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKStatistics>"
)

# Create imported target ITKMesh
add_library(ITKMesh STATIC IMPORTED)

set_target_properties(ITKMesh PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKTransform>"
)

# Create imported target itkzlib
add_library(itkzlib STATIC IMPORTED)

# Create imported target ITKMetaIO
add_library(ITKMetaIO STATIC IMPORTED)

set_target_properties(ITKMetaIO PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkzlib"
)

# Create imported target ITKSpatialObjects
add_library(ITKSpatialObjects STATIC IMPORTED)

set_target_properties(ITKSpatialObjects PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKTransform;\$<LINK_ONLY:ITKCommon>;\$<LINK_ONLY:ITKMesh>"
)

# Create imported target ITKPath
add_library(ITKPath STATIC IMPORTED)

set_target_properties(ITKPath PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKCommon>"
)

# Create imported target ITKQuadEdgeMesh
add_library(ITKQuadEdgeMesh STATIC IMPORTED)

set_target_properties(ITKQuadEdgeMesh PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKMesh>"
)

# Create imported target ITKIOImageBase
add_library(ITKIOImageBase STATIC IMPORTED)

set_target_properties(ITKIOImageBase PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon"
)

# Create imported target ITKOptimizers
add_library(ITKOptimizers STATIC IMPORTED)

set_target_properties(ITKOptimizers PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKStatistics"
)

# Create imported target ITKPolynomials
add_library(ITKPolynomials STATIC IMPORTED)

set_target_properties(ITKPolynomials PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon"
)

# Create imported target ITKBiasCorrection
add_library(ITKBiasCorrection STATIC IMPORTED)

set_target_properties(ITKBiasCorrection PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKCommon>"
)

# Create imported target ITKBioCell
add_library(ITKBioCell STATIC IMPORTED)

set_target_properties(ITKBioCell PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKMesh;\$<LINK_ONLY:ITKCommon>"
)

# Create imported target ITKDICOMParser
add_library(ITKDICOMParser STATIC IMPORTED)

# Create imported target ITKEXPAT
add_library(ITKEXPAT STATIC IMPORTED)

# Create imported target ITKIOXML
add_library(ITKIOXML STATIC IMPORTED)

set_target_properties(ITKIOXML PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKIOImageBase;\$<LINK_ONLY:ITKEXPAT>"
)

# Create imported target ITKIOSpatialObjects
add_library(ITKIOSpatialObjects STATIC IMPORTED)

set_target_properties(ITKIOSpatialObjects PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOXML>;\$<LINK_ONLY:ITKMesh>;\$<LINK_ONLY:ITKSpatialObjects>"
)

# Create imported target ITKFEM
add_library(ITKFEM STATIC IMPORTED)

set_target_properties(ITKFEM PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKMesh;ITKOptimizers;ITKMetaIO"
)

# Create imported target gdcmCommon
add_library(gdcmCommon STATIC IMPORTED)

# Create imported target gdcmDICT
add_library(gdcmDICT STATIC IMPORTED)

set_target_properties(gdcmDICT PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:gdcmDSED>;\$<LINK_ONLY:gdcmIOD>"
)

# Create imported target gdcmDSED
add_library(gdcmDSED STATIC IMPORTED)

set_target_properties(gdcmDSED PROPERTIES
  INTERFACE_LINK_LIBRARIES "gdcmCommon;\$<LINK_ONLY:itkzlib>"
)

# Create imported target gdcmIOD
add_library(gdcmIOD STATIC IMPORTED)

set_target_properties(gdcmIOD PROPERTIES
  INTERFACE_LINK_LIBRARIES "gdcmDSED;gdcmCommon;\$<LINK_ONLY:ITKEXPAT>"
)

# Create imported target gdcmMEXD
add_library(gdcmMEXD STATIC IMPORTED)

set_target_properties(gdcmMEXD PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:gdcmMSFF>;\$<LINK_ONLY:gdcmDICT>;\$<LINK_ONLY:gdcmDSED>;\$<LINK_ONLY:gdcmIOD>;\$<LINK_ONLY:gdcmsocketxx>"
)

# Create imported target gdcmMSFF
add_library(gdcmMSFF STATIC IMPORTED)

set_target_properties(gdcmMSFF PROPERTIES
  INTERFACE_LINK_LIBRARIES "gdcmIOD;gdcmDSED;gdcmDICT;\$<LINK_ONLY:gdcmjpeg8>;\$<LINK_ONLY:gdcmjpeg12>;\$<LINK_ONLY:gdcmjpeg16>;\$<LINK_ONLY:itkgdcmopenjp2>;\$<LINK_ONLY:gdcmcharls>;\$<LINK_ONLY:gdcmuuid>"
)

# Create imported target gdcmcharls
add_library(gdcmcharls STATIC IMPORTED)

# Create imported target gdcmjpeg12
add_library(gdcmjpeg12 STATIC IMPORTED)

# Create imported target gdcmjpeg16
add_library(gdcmjpeg16 STATIC IMPORTED)

# Create imported target gdcmjpeg8
add_library(gdcmjpeg8 STATIC IMPORTED)

# Create imported target itkgdcmopenjp2
add_library(itkgdcmopenjp2 STATIC IMPORTED)

# Create imported target gdcmsocketxx
add_library(gdcmsocketxx STATIC IMPORTED)

# Create imported target gdcmuuid
add_library(gdcmuuid STATIC IMPORTED)

# Create imported target ITKznz
add_library(ITKznz STATIC IMPORTED)

# Create imported target ITKniftiio
add_library(ITKniftiio STATIC IMPORTED)

# Create imported target ITKgiftiio
add_library(ITKgiftiio STATIC IMPORTED)

# Create imported target GTest::GTest
add_library(GTest::GTest STATIC IMPORTED)

set_target_properties(GTest::GTest PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/GoogleTest/src/itkgoogletest/googletest/include"
)

# Create imported target GTest::Main
add_library(GTest::Main STATIC IMPORTED)

set_target_properties(GTest::Main PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/GoogleTest/src/itkgoogletest/googletest/include"
)

# Create imported target hdf5-static
add_library(hdf5-static STATIC IMPORTED)

set_target_properties(hdf5-static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/ITKbin/Modules/ThirdParty/HDF5/src/itkhdf5/src;/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/HDF5/src/itkhdf5/src"
  INTERFACE_LINK_LIBRARIES "m;dl;itkzlib"
)

# Create imported target hdf5_cpp-static
add_library(hdf5_cpp-static STATIC IMPORTED)

set_target_properties(hdf5_cpp-static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/kit/Documents/ITK/ITKbin/Modules/ThirdParty/HDF5/src/itkhdf5/c++/src;/Users/kit/Documents/ITK/InsightToolKit/Modules/ThirdParty/HDF5/src/itkhdf5/c++/src"
  INTERFACE_LINK_LIBRARIES "hdf5-static"
)

# Create imported target ITKIOBMP
add_library(ITKIOBMP STATIC IMPORTED)

set_target_properties(ITKIOBMP PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIOBioRad
add_library(ITKIOBioRad STATIC IMPORTED)

set_target_properties(ITKIOBioRad PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIOBruker
add_library(ITKIOBruker STATIC IMPORTED)

set_target_properties(ITKIOBruker PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIOCSV
add_library(ITKIOCSV STATIC IMPORTED)

set_target_properties(ITKIOCSV PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIOGDCM
add_library(ITKIOGDCM STATIC IMPORTED)

set_target_properties(ITKIOGDCM PROPERTIES
  INTERFACE_LINK_LIBRARIES "gdcmDICT;gdcmMSFF;\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIOIPL
add_library(ITKIOIPL STATIC IMPORTED)

set_target_properties(ITKIOIPL PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIOGE
add_library(ITKIOGE STATIC IMPORTED)

set_target_properties(ITKIOGE PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKIOIPL;\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIOGIPL
add_library(ITKIOGIPL STATIC IMPORTED)

set_target_properties(ITKIOGIPL PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>;\$<LINK_ONLY:itkzlib>"
)

# Create imported target ITKIOHDF5
add_library(ITKIOHDF5 STATIC IMPORTED)

set_target_properties(ITKIOHDF5 PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:hdf5_cpp-static>;\$<LINK_ONLY:hdf5-static>;\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target itkjpeg
add_library(itkjpeg STATIC IMPORTED)

# Create imported target ITKIOJPEG
add_library(ITKIOJPEG STATIC IMPORTED)

set_target_properties(ITKIOJPEG PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>;\$<LINK_ONLY:itkjpeg>"
)

# Create imported target itktiff
add_library(itktiff STATIC IMPORTED)

set_target_properties(itktiff PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkzlib;itkjpeg;-lm"
)

# Create imported target ITKIOTIFF
add_library(ITKIOTIFF STATIC IMPORTED)

set_target_properties(ITKIOTIFF PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>;\$<LINK_ONLY:itktiff>"
)

# Create imported target ITKIOLSM
add_library(ITKIOLSM STATIC IMPORTED)

set_target_properties(ITKIOLSM PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>;\$<LINK_ONLY:ITKIOTIFF>;\$<LINK_ONLY:itktiff>"
)

# Create imported target itkminc2
add_library(itkminc2 STATIC IMPORTED)

# Create imported target ITKIOMINC
add_library(ITKIOMINC STATIC IMPORTED)

set_target_properties(ITKIOMINC PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKIOImageBase;\$<LINK_ONLY:itkminc2>"
)

# Create imported target ITKIOMRC
add_library(ITKIOMRC STATIC IMPORTED)

set_target_properties(ITKIOMRC PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIOMesh
add_library(ITKIOMesh STATIC IMPORTED)

set_target_properties(ITKIOMesh PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:itkdouble-conversion>;\$<LINK_ONLY:ITKgiftiio>;\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIOMeta
add_library(ITKIOMeta STATIC IMPORTED)

set_target_properties(ITKIOMeta PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKMetaIO;\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIONIFTI
add_library(ITKIONIFTI STATIC IMPORTED)

set_target_properties(ITKIONIFTI PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>;\$<LINK_ONLY:ITKznz>;\$<LINK_ONLY:ITKniftiio>;\$<LINK_ONLY:ITKTransform>"
)

# Create imported target ITKNrrdIO
add_library(ITKNrrdIO STATIC IMPORTED)

set_target_properties(ITKNrrdIO PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkzlib"
)

# Create imported target ITKIONRRD
add_library(ITKIONRRD STATIC IMPORTED)

set_target_properties(ITKIONRRD PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>;\$<LINK_ONLY:ITKNrrdIO>"
)

# Create imported target itkpng
add_library(itkpng STATIC IMPORTED)

set_target_properties(itkpng PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkzlib"
)

# Create imported target ITKIOPNG
add_library(ITKIOPNG STATIC IMPORTED)

set_target_properties(ITKIOPNG PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>;\$<LINK_ONLY:itkpng>"
)

# Create imported target ITKIOSiemens
add_library(ITKIOSiemens STATIC IMPORTED)

set_target_properties(ITKIOSiemens PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOIPL>;\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKIOStimulate
add_library(ITKIOStimulate STATIC IMPORTED)

set_target_properties(ITKIOStimulate PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKTransformFactory
add_library(ITKTransformFactory STATIC IMPORTED)

set_target_properties(ITKTransformFactory PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon;ITKTransform"
)

# Create imported target ITKIOTransformBase
add_library(ITKIOTransformBase STATIC IMPORTED)

set_target_properties(ITKIOTransformBase PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon;ITKTransform;ITKTransformFactory"
)

# Create imported target ITKIOTransformHDF5
add_library(ITKIOTransformHDF5 STATIC IMPORTED)

set_target_properties(ITKIOTransformHDF5 PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKIOTransformBase;\$<LINK_ONLY:hdf5_cpp-static>;\$<LINK_ONLY:hdf5-static>"
)

# Create imported target ITKIOTransformInsightLegacy
add_library(ITKIOTransformInsightLegacy STATIC IMPORTED)

set_target_properties(ITKIOTransformInsightLegacy PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKIOTransformBase;\$<LINK_ONLY:itkdouble-conversion>"
)

# Create imported target ITKIOTransformMatlab
add_library(ITKIOTransformMatlab STATIC IMPORTED)

set_target_properties(ITKIOTransformMatlab PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKIOTransformBase"
)

# Create imported target ITKIOVTK
add_library(ITKIOVTK STATIC IMPORTED)

set_target_properties(ITKIOVTK PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKIOImageBase>"
)

# Create imported target ITKKLMRegionGrowing
add_library(ITKKLMRegionGrowing STATIC IMPORTED)

set_target_properties(ITKKLMRegionGrowing PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon"
)

# Create imported target itklbfgs
add_library(itklbfgs STATIC IMPORTED)

# Create imported target ITKOptimizersv4
add_library(ITKOptimizersv4 STATIC IMPORTED)

set_target_properties(ITKOptimizersv4 PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKOptimizers;\$<LINK_ONLY:itklbfgs>"
)

# Create imported target itkTestDriver
add_executable(itkTestDriver IMPORTED)

# Create imported target ITKVTK
add_library(ITKVTK STATIC IMPORTED)

set_target_properties(ITKVTK PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ITKCommon>"
)

# Create imported target ITKVideoCore
add_library(ITKVideoCore STATIC IMPORTED)

set_target_properties(ITKVideoCore PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon"
)

# Create imported target ITKVideoIO
add_library(ITKVideoIO STATIC IMPORTED)

set_target_properties(ITKVideoIO PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKIOImageBase;ITKVideoCore"
)

# Create imported target ITKWatersheds
add_library(ITKWatersheds STATIC IMPORTED)

set_target_properties(ITKWatersheds PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKCommon;ITKStatistics;ITKTransform;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath"
)

# Import target "itkdouble-conversion" for configuration "Release"
set_property(TARGET itkdouble-conversion APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkdouble-conversion PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkdouble-conversion-4.13.a"
  )

# Import target "itksys" for configuration "Release"
set_property(TARGET itksys APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itksys PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitksys-4.13.a"
  )

# Import target "itkvcl" for configuration "Release"
set_property(TARGET itkvcl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkvcl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "m"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkvcl-4.13.a"
  )

# Import target "itkv3p_netlib" for configuration "Release"
set_property(TARGET itkv3p_netlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkv3p_netlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "m"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkv3p_netlib-4.13.a"
  )

# Import target "itktestlib" for configuration "Release"
set_property(TARGET itktestlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itktestlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkvcl"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitktestlib-4.13.a"
  )

# Import target "itkvnl" for configuration "Release"
set_property(TARGET itkvnl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkvnl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkvcl"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkvnl-4.13.a"
  )

# Import target "itkvnl_algo" for configuration "Release"
set_property(TARGET itkvnl_algo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkvnl_algo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itknetlib;itkv3p_netlib;itkvnl"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkvnl_algo-4.13.a"
  )

# Import target "itknetlib" for configuration "Release"
set_property(TARGET itknetlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itknetlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "m"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitknetlib-4.13.a"
  )

# Import target "ITKVNLInstantiation" for configuration "Release"
set_property(TARGET ITKVNLInstantiation APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKVNLInstantiation PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKVNLInstantiation-4.13.a"
  )

# Import target "ITKCommon" for configuration "Release"
set_property(TARGET ITKCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKCommon-4.13.a"
  )

# Import target "itkNetlibSlatec" for configuration "Release"
set_property(TARGET itkNetlibSlatec APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkNetlibSlatec PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkNetlibSlatec-4.13.a"
  )

# Import target "ITKStatistics" for configuration "Release"
set_property(TARGET ITKStatistics APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKStatistics PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKStatistics-4.13.a"
  )

# Import target "ITKTransform" for configuration "Release"
set_property(TARGET ITKTransform APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKTransform PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKTransform-4.13.a"
  )

# Import target "ITKLabelMap" for configuration "Release"
set_property(TARGET ITKLabelMap APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKLabelMap PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKLabelMap-4.13.a"
  )

# Import target "ITKMesh" for configuration "Release"
set_property(TARGET ITKMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKMesh PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKMesh-4.13.a"
  )

# Import target "itkzlib" for configuration "Release"
set_property(TARGET itkzlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkzlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkzlib-4.13.a"
  )

# Import target "ITKMetaIO" for configuration "Release"
set_property(TARGET ITKMetaIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKMetaIO PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKMetaIO-4.13.a"
  )

# Import target "ITKSpatialObjects" for configuration "Release"
set_property(TARGET ITKSpatialObjects APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKSpatialObjects PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKSpatialObjects-4.13.a"
  )

# Import target "ITKPath" for configuration "Release"
set_property(TARGET ITKPath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKPath PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKPath-4.13.a"
  )

# Import target "ITKQuadEdgeMesh" for configuration "Release"
set_property(TARGET ITKQuadEdgeMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKQuadEdgeMesh PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKQuadEdgeMesh-4.13.a"
  )

# Import target "ITKIOImageBase" for configuration "Release"
set_property(TARGET ITKIOImageBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOImageBase PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOImageBase-4.13.a"
  )

# Import target "ITKOptimizers" for configuration "Release"
set_property(TARGET ITKOptimizers APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKOptimizers PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKOptimizers-4.13.a"
  )

# Import target "ITKPolynomials" for configuration "Release"
set_property(TARGET ITKPolynomials APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKPolynomials PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKPolynomials-4.13.a"
  )

# Import target "ITKBiasCorrection" for configuration "Release"
set_property(TARGET ITKBiasCorrection APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKBiasCorrection PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKBiasCorrection-4.13.a"
  )

# Import target "ITKBioCell" for configuration "Release"
set_property(TARGET ITKBioCell APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKBioCell PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKBioCell-4.13.a"
  )

# Import target "ITKDICOMParser" for configuration "Release"
set_property(TARGET ITKDICOMParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKDICOMParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKDICOMParser-4.13.a"
  )

# Import target "ITKEXPAT" for configuration "Release"
set_property(TARGET ITKEXPAT APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKEXPAT PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKEXPAT-4.13.a"
  )

# Import target "ITKIOXML" for configuration "Release"
set_property(TARGET ITKIOXML APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOXML PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOXML-4.13.a"
  )

# Import target "ITKIOSpatialObjects" for configuration "Release"
set_property(TARGET ITKIOSpatialObjects APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOSpatialObjects PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOSpatialObjects-4.13.a"
  )

# Import target "ITKFEM" for configuration "Release"
set_property(TARGET ITKFEM APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKFEM PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKFEM-4.13.a"
  )

# Import target "gdcmCommon" for configuration "Release"
set_property(TARGET gdcmCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmCommon-4.13.a"
  )

# Import target "gdcmDICT" for configuration "Release"
set_property(TARGET gdcmDICT APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmDICT PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmDICT-4.13.a"
  )

# Import target "gdcmDSED" for configuration "Release"
set_property(TARGET gdcmDSED APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmDSED PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmDSED-4.13.a"
  )

# Import target "gdcmIOD" for configuration "Release"
set_property(TARGET gdcmIOD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmIOD PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmIOD-4.13.a"
  )

# Import target "gdcmMEXD" for configuration "Release"
set_property(TARGET gdcmMEXD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmMEXD PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmMEXD-4.13.a"
  )

# Import target "gdcmMSFF" for configuration "Release"
set_property(TARGET gdcmMSFF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmMSFF PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmMSFF-4.13.a"
  )

# Import target "gdcmcharls" for configuration "Release"
set_property(TARGET gdcmcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmcharls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmcharls-4.13.a"
  )

# Import target "gdcmjpeg12" for configuration "Release"
set_property(TARGET gdcmjpeg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmjpeg12 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmjpeg12-4.13.a"
  )

# Import target "gdcmjpeg16" for configuration "Release"
set_property(TARGET gdcmjpeg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmjpeg16 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmjpeg16-4.13.a"
  )

# Import target "gdcmjpeg8" for configuration "Release"
set_property(TARGET gdcmjpeg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmjpeg8 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmjpeg8-4.13.a"
  )

# Import target "itkgdcmopenjp2" for configuration "Release"
set_property(TARGET itkgdcmopenjp2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkgdcmopenjp2 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "m"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmopenjp2-4.13.a"
  )

# Import target "gdcmsocketxx" for configuration "Release"
set_property(TARGET gdcmsocketxx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmsocketxx PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmsocketxx-4.13.a"
  )

# Import target "gdcmuuid" for configuration "Release"
set_property(TARGET gdcmuuid APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmuuid PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgdcmuuid-4.13.a"
  )

# Import target "ITKznz" for configuration "Release"
set_property(TARGET ITKznz APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKznz PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkzlib"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKznz-4.13.a"
  )

# Import target "ITKniftiio" for configuration "Release"
set_property(TARGET ITKniftiio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKniftiio PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKznz;-lm"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKniftiio-4.13.a"
  )

# Import target "ITKgiftiio" for configuration "Release"
set_property(TARGET ITKgiftiio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKgiftiio PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKEXPAT;ITKznz;ITKniftiio"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKgiftiio-4.13.a"
  )

# Import target "GTest::GTest" for configuration "Release"
set_property(TARGET GTest::GTest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GTest::GTest PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgtest-4.13.a"
  )

# Import target "GTest::Main" for configuration "Release"
set_property(TARGET GTest::Main APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GTest::Main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "GTest::GTest"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkgtest_main-4.13.a"
  )

# Import target "hdf5-static" for configuration "Release"
set_property(TARGET hdf5-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdf5-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkhdf5.a"
  )

# Import target "hdf5_cpp-static" for configuration "Release"
set_property(TARGET hdf5_cpp-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdf5_cpp-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkhdf5_cpp.a"
  )

# Import target "ITKIOBMP" for configuration "Release"
set_property(TARGET ITKIOBMP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOBMP PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOBMP-4.13.a"
  )

# Import target "ITKIOBioRad" for configuration "Release"
set_property(TARGET ITKIOBioRad APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOBioRad PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOBioRad-4.13.a"
  )

# Import target "ITKIOBruker" for configuration "Release"
set_property(TARGET ITKIOBruker APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOBruker PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOBruker-4.13.a"
  )

# Import target "ITKIOCSV" for configuration "Release"
set_property(TARGET ITKIOCSV APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOCSV PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOCSV-4.13.a"
  )

# Import target "ITKIOGDCM" for configuration "Release"
set_property(TARGET ITKIOGDCM APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOGDCM PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOGDCM-4.13.a"
  )

# Import target "ITKIOIPL" for configuration "Release"
set_property(TARGET ITKIOIPL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOIPL PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOIPL-4.13.a"
  )

# Import target "ITKIOGE" for configuration "Release"
set_property(TARGET ITKIOGE APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOGE PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOGE-4.13.a"
  )

# Import target "ITKIOGIPL" for configuration "Release"
set_property(TARGET ITKIOGIPL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOGIPL PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOGIPL-4.13.a"
  )

# Import target "ITKIOHDF5" for configuration "Release"
set_property(TARGET ITKIOHDF5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOHDF5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOHDF5-4.13.a"
  )

# Import target "itkjpeg" for configuration "Release"
set_property(TARGET itkjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkjpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkjpeg-4.13.a"
  )

# Import target "ITKIOJPEG" for configuration "Release"
set_property(TARGET ITKIOJPEG APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOJPEG PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOJPEG-4.13.a"
  )

# Import target "itktiff" for configuration "Release"
set_property(TARGET itktiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itktiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitktiff-4.13.a"
  )

# Import target "ITKIOTIFF" for configuration "Release"
set_property(TARGET ITKIOTIFF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOTIFF PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOTIFF-4.13.a"
  )

# Import target "ITKIOLSM" for configuration "Release"
set_property(TARGET ITKIOLSM APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOLSM PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOLSM-4.13.a"
  )

# Import target "itkminc2" for configuration "Release"
set_property(TARGET itkminc2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkminc2 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5_cpp-static;hdf5-static;itkzlib;m;dl"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkminc2-4.13.a"
  )

# Import target "ITKIOMINC" for configuration "Release"
set_property(TARGET ITKIOMINC APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOMINC PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOMINC-4.13.a"
  )

# Import target "ITKIOMRC" for configuration "Release"
set_property(TARGET ITKIOMRC APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOMRC PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOMRC-4.13.a"
  )

# Import target "ITKIOMesh" for configuration "Release"
set_property(TARGET ITKIOMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOMesh PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOMesh-4.13.a"
  )

# Import target "ITKIOMeta" for configuration "Release"
set_property(TARGET ITKIOMeta APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOMeta PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOMeta-4.13.a"
  )

# Import target "ITKIONIFTI" for configuration "Release"
set_property(TARGET ITKIONIFTI APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIONIFTI PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIONIFTI-4.13.a"
  )

# Import target "ITKNrrdIO" for configuration "Release"
set_property(TARGET ITKNrrdIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKNrrdIO PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKNrrdIO-4.13.a"
  )

# Import target "ITKIONRRD" for configuration "Release"
set_property(TARGET ITKIONRRD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIONRRD PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIONRRD-4.13.a"
  )

# Import target "itkpng" for configuration "Release"
set_property(TARGET itkpng APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkpng PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitkpng-4.13.a"
  )

# Import target "ITKIOPNG" for configuration "Release"
set_property(TARGET ITKIOPNG APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOPNG PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOPNG-4.13.a"
  )

# Import target "ITKIOSiemens" for configuration "Release"
set_property(TARGET ITKIOSiemens APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOSiemens PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOSiemens-4.13.a"
  )

# Import target "ITKIOStimulate" for configuration "Release"
set_property(TARGET ITKIOStimulate APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOStimulate PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOStimulate-4.13.a"
  )

# Import target "ITKTransformFactory" for configuration "Release"
set_property(TARGET ITKTransformFactory APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKTransformFactory PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKTransformFactory-4.13.a"
  )

# Import target "ITKIOTransformBase" for configuration "Release"
set_property(TARGET ITKIOTransformBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOTransformBase PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOTransformBase-4.13.a"
  )

# Import target "ITKIOTransformHDF5" for configuration "Release"
set_property(TARGET ITKIOTransformHDF5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOTransformHDF5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOTransformHDF5-4.13.a"
  )

# Import target "ITKIOTransformInsightLegacy" for configuration "Release"
set_property(TARGET ITKIOTransformInsightLegacy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOTransformInsightLegacy PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOTransformInsightLegacy-4.13.a"
  )

# Import target "ITKIOTransformMatlab" for configuration "Release"
set_property(TARGET ITKIOTransformMatlab APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOTransformMatlab PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOTransformMatlab-4.13.a"
  )

# Import target "ITKIOVTK" for configuration "Release"
set_property(TARGET ITKIOVTK APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOVTK PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKIOVTK-4.13.a"
  )

# Import target "ITKKLMRegionGrowing" for configuration "Release"
set_property(TARGET ITKKLMRegionGrowing APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKKLMRegionGrowing PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKKLMRegionGrowing-4.13.a"
  )

# Import target "itklbfgs" for configuration "Release"
set_property(TARGET itklbfgs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itklbfgs PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libitklbfgs-4.13.a"
  )

# Import target "ITKOptimizersv4" for configuration "Release"
set_property(TARGET ITKOptimizersv4 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKOptimizersv4 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKOptimizersv4-4.13.a"
  )

# Import target "itkTestDriver" for configuration "Release"
set_property(TARGET itkTestDriver APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkTestDriver PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/bin/itkTestDriver"
  )

# Import target "ITKVTK" for configuration "Release"
set_property(TARGET ITKVTK APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKVTK PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKVTK-4.13.a"
  )

# Import target "ITKVideoCore" for configuration "Release"
set_property(TARGET ITKVideoCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKVideoCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKVideoCore-4.13.a"
  )

# Import target "ITKVideoIO" for configuration "Release"
set_property(TARGET ITKVideoIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKVideoIO PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKVideoIO-4.13.a"
  )

# Import target "ITKWatersheds" for configuration "Release"
set_property(TARGET ITKWatersheds APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKWatersheds PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/kit/Documents/ITK/ITKbin/lib/libITKWatersheds-4.13.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
